/*
 * Copyright 2024 EPAM Systems
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef RPI5_SCMI_RESOURCES_H
#define RPI5_SCMI_RESOURCES_H

#include <assert.h>
#include <drivers/scmi-msg.h>

#include "rpi5_scmi_devices.h"

struct scmi_reset {
	const char *name;
	uint32_t id;
};
enum rcar_scmi_rst_offset {
	RPI5_SCMIRST_PCIE1_1,	/* 0 */
	RPI5_SCMIRST_PCIE1_2,	/* 1 */
	RPI5_SCMIRST_PCIE2_1,	/* 2 */
	RPI5_SCMIRST_PCIE2_2,	/* 3 */
	RPI5_SCMIRST_MAX
};

struct scmi_device {
	int *rsts;
	int *pins;
};

typedef uint16_t scmi_umask_t;

typedef scmi_umask_t scmi_perm_t;

static inline bool scmi_permission_granted(scmi_perm_t perm, uint32_t agent_id)
{
	assert(agent_id < plat_scmi_agent_count());
	return perm & (1 << agent_id);
}

enum rpi5_scmi_pins {
	RPI5_SCMI_PIN_GPIO_0,
	RPI5_SCMI_PIN_GPIO_1,
	RPI5_SCMI_PIN_GPIO_2,
	RPI5_SCMI_PIN_GPIO_3,
	RPI5_SCMI_PIN_GPIO_4,
	RPI5_SCMI_PIN_GPIO_5,
	RPI5_SCMI_PIN_GPIO_6,
	RPI5_SCMI_PIN_GPIO_7,
	RPI5_SCMI_PIN_GPIO_8,
	RPI5_SCMI_PIN_GPIO_9,
	RPI5_SCMI_PIN_GPIO_10,
	RPI5_SCMI_PIN_GPIO_11,
	RPI5_SCMI_PIN_GPIO_12,
	RPI5_SCMI_PIN_GPIO_13,
	RPI5_SCMI_PIN_GPIO_14,
	RPI5_SCMI_PIN_GPIO_15,
	RPI5_SCMI_PIN_GPIO_16,
	RPI5_SCMI_PIN_GPIO_17,
	RPI5_SCMI_PIN_GPIO_18,
	RPI5_SCMI_PIN_GPIO_19,
	RPI5_SCMI_PIN_GPIO_20,
	RPI5_SCMI_PIN_GPIO_21,
	RPI5_SCMI_PIN_GPIO_22,
	RPI5_SCMI_PIN_GPIO_23,
	RPI5_SCMI_PIN_GPIO_24,
	RPI5_SCMI_PIN_GPIO_25,
	RPI5_SCMI_PIN_GPIO_26,
	RPI5_SCMI_PIN_GPIO_27,
	RPI5_SCMI_PIN_GPIO_28,
	RPI5_SCMI_PIN_GPIO_29,
	RPI5_SCMI_PIN_GPIO_30,
	RPI5_SCMI_PIN_GPIO_31,
	RPI5_SCMI_PIN_GPIO_32,
	RPI5_SCMI_PIN_GPIO_33,
	RPI5_SCMI_PIN_GPIO_34,
	RPI5_SCMI_PIN_GPIO_35,
	RPI5_SCMI_PIN_GPIO_36,
	RPI5_SCMI_PIN_GPIO_37,
	RPI5_SCMI_PIN_GPIO_38,
	RPI5_SCMI_PIN_GPIO_39,
	RPI5_SCMI_PIN_GPIO_40,
	RPI5_SCMI_PIN_GPIO_41,
	RPI5_SCMI_PIN_GPIO_42,
	RPI5_SCMI_PIN_GPIO_43,
	RPI5_SCMI_PIN_GPIO_44,
	RPI5_SCMI_PIN_GPIO_45,
	RPI5_SCMI_PIN_GPIO_46,
	RPI5_SCMI_PIN_GPIO_47,
	RPI5_SCMI_PIN_GPIO_48,
	RPI5_SCMI_PIN_GPIO_49,
	RPI5_SCMI_PIN_GPIO_50,
	RPI5_SCMI_PIN_GPIO_51,
	RPI5_SCMI_PIN_GPIO_52,
	RPI5_SCMI_PIN_GPIO_53,
	RPI5_SCMI_PIN_EMMC_CMD,
	RPI5_SCMI_PIN_EMMC_DS,
	RPI5_SCMI_PIN_EMMC_CLK,
	RPI5_SCMI_PIN_EMMC_DAT0,
	RPI5_SCMI_PIN_EMMC_DAT1,
	RPI5_SCMI_PIN_EMMC_DAT2,
	RPI5_SCMI_PIN_EMMC_DAT3,
	RPI5_SCMI_PIN_EMMC_DAT4,
	RPI5_SCMI_PIN_EMMC_DAT5,
	RPI5_SCMI_PIN_EMMC_DAT6,
	RPI5_SCMI_PIN_EMMC_DAT7,
	RPI5_SCMI_PIN_MAX
};
extern scmi_perm_t rpi_scmi_perm_resets[];

#endif /* RPI5_SCMI_RESOURCES_H */
